# Generated by Django 5.1.6 on 2025-02-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
