# Generated by Django 5.1.6 on 2025-02-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('PA', 'Paid'), ('D', 'Done'), ('M', 'Missed'), ('C', 'Cancelled'), ('DE', 'Delayed')], default='PE', max_length=50),
        ),
    ]
