# Generated by Django 5.1.6 on 2025-03-13 21:07
from django.utils import timezone
from django.db import migrations, models

def set_created_at(apps, schema_editor):
    appointments = apps.get_model('appointments', 'Appointment')
    for obj in appointments.objects.all():
        obj.created_at = timezone.now()
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RunPython(set_created_at)
    ]
    
