# Generated by Django 5.1.6 on 2025-02-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_uuid_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('D', 'Doctor'), ('P', 'Patient'), ('A', 'ADMIN')], default='P', max_length=50),
        ),
    ]
