# Generated by Django 5.1.6 on 2025-10-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientfolder_patientfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientfile',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='patientfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
