# Generated by Django 5.1.6 on 2025-11-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('D', 'Doctor'), ('P', 'Patient')], max_length=50),
        ),
    ]
