# Generated by Django 5.1.6 on 2025-11-07 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_alter_doctor_is_verified'),
        ('patients', '0003_rename_title_patientfile_name_patientfile_updated_at'),
        ('reviews', '0002_alter_comment_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctors.doctor'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('doctor', 'patient'), name='unique_review_per_doctor_patient'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='appointment',
        ),
    ]
