# Generated by Django 5.1.6 on 2025-02-13 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_status_alter_doctor_about_alter_doctor_fees_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Specialty', 'verbose_name_plural': 'Specialties'},
        ),
    ]
