# Generated by Django 5.1.6 on 2025-02-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_schedule_doctor_alter_workinghours_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'WED'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=50),
        ),
    ]
