# Generated by Django 5.1.6 on 2025-02-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_specialty_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='specialty/icons'),
        ),
    ]
