# Generated by Django 5.1.6 on 2025-02-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghours',
            options={'verbose_name_plural': 'Working Hours'},
        ),
    ]
