# Generated by Django 5.1.6 on 2025-02-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_alter_workinghours_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='degree_document',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='doctor/degree'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_verified',
            field=models.BooleanField(db_default=False),
        ),
    ]
