# Generated by Django 5.1.6 on 2025-03-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_doctor_degree_document_doctor_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinghours',
            old_name='max_patients',
            new_name='patient_left',
        ),
        migrations.AddField(
            model_name='doctor',
            name='address_line1',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='doctor',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
