# Generated by Django 5.1.6 on 2025-03-17 01:16

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_rename_max_patients_workinghours_patient_left_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='doctor',
            managers=[
                ('available', django.db.models.manager.Manager()),
            ],
        ),
    ]
