# Generated by Django 5.1.6 on 2025-03-17 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_alter_doctor_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='doctor',
            managers=[
            ],
        ),
    ]
