# Generated by Django 5.1.6 on 2025-03-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_alter_doctor_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
